### ISSUE TITLE
Has anyone thought and implemented a multithreaded or parallel or distributed version of dopamine?

### ISSUE THREAD

**Issue by shyamalschandra** [google/dopamine#6] opened 2018-08-28 15:20 UTC
Has anyone thought and implemented a multithreaded or parallel or distributed version of dopamine?  If not, I will start the process of doing so.  If so, please let me know.  Thanks!

**Comment by smoitra87** [comment] 2018-08-29 15:18
Thanks for the suggestion. Presently, we are by design trying to keep the codebase light and flexible. So any distributed implementations are not on our radar. Closing this issue for now.

**Closed by smoitra87** 2018-08-29 15:18 UTC
