### ISSUE TITLE
C51 Cartpole Tutorial No Longer Works

### ISSUE THREAD

**Issue by RylanSchaeffer** [google/dopamine#161] opened 2020-12-21 23:39 UTC
`atari_lib.py`'s `create_atari_environment()` requires the game name, but the C51 Colab tutorial has some error such that this information does not reach the function call.

```
---------------------------------------------------------------------------

AssertionError                            Traceback (most recent call last)

<ipython-input-5-eb14815f5489> in <module>()
      1 # @title Train C51 on Cartpole
----> 2 c51_runner = run_experiment.create_runner(C51_PATH, schedule='continuous_train')
      3 print('Will train agent, please be patient, may be a while...')
      4 c51_runner.run_experiment()
      5 print('Done training!')

15 frames

/usr/local/lib/python3.6/dist-packages/dopamine/discrete_domains/atari_lib.py in create_atari_environment(game_name, sticky_actions)
     91     An Atari 2600 environment with some standard preprocessing.
     92   """
---> 93   assert game_name is not None
     94   game_version = 'v0' if sticky_actions else 'v4'
     95   full_game_name = '{}NoFrameskip-{}'.format(game_name, game_version)

AssertionError: 
  In call to configurable 'create_atari_environment' (<function create_atari_environment at 0x7ff8f9e25e18>)
  In call to configurable 'Runner' (<class 'dopamine.discrete_domains.run_experiment.Runner'>)
  In call to configurable 'TrainRunner' (<class 'dopamine.discrete_domains.run_experiment.TrainRunner'>)
  In call to configurable 'create_runner' (<function create_runner at 0x7ff8a0f10598>)
```

**Comment by RylanSchaeffer** [comment] 2020-12-22 00:23
Ok this is weird. The error only exists if I do *not* parse the DQN config. If I parse the DQN config, no error appears. Why is this?

**Comment by RylanSchaeffer** [comment] 2020-12-22 00:28
The error is due to `Runner.create_environment_fn = @gym_lib.create_gym_environment` in the C51 config. Switching to `TrainRunner.create_environment_fn = @gym_lib.create_gym_environment` removed the error.

This tells me that gin configurations are stateful and consequently potentially deceptive.

**Comment by psc-g** [comment] 2021-04-09 15:22
thanks for pointing this out! i will fix it now.
the issue is that gin injections get overriden if the parameter is set explicitly by the caller function. this means that if you set `Runner.create_environment_fn = @gym_lib.create_gym_environment`, it will get overriden by the call from `TrainRunner`'s init here:
https://github.com/google/dopamine/blob/master/dopamine/discrete_domains/run_experiment.py#L551

it's default value is `atari_lib.create_atari_environment` so that's what ends up being used.

setting `TrainRunner.create_environment_fn = @gym_lib.create_gym_environment` as you point out fixes it.

sorry for that, and will fix it now!

**Comment by psc-g** [comment] 2021-05-07 19:17
sorry for delay, fix will be pushed today or monday.

**Comment by psc-g** [comment] 2021-05-07 20:11
fixed in https://github.com/google/dopamine/commit/baf4b8273dce64fcd865185b29f22070a5d96a35

**Closed by psc-g** 2021-05-07 20:11 UTC
